"""Add bookings table and OTP fields (verification_otp, reset_otp)

Revision ID: e5a02d68c3d4
Revises: 8d21ef732dc0
Create Date: 2025-09-13 21:24:38.879512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a02d68c3d4'
down_revision = '8d21ef732dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('verification_otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_otp_expires_at')
        batch_op.drop_column('reset_otp')
        batch_op.drop_column('verification_otp_expires_at')
        batch_op.drop_column('verification_otp')

    # ### end Alembic commands ###
